### ISSUE TITLE
Review master branch notebooks

### ISSUE THREAD

**Issue by johnbradley** [dleehr/scicomp-python#4]
#### Inconsistent spacing of parameters ([17],[18])

```
data.iloc[0:4,0:2]
data.iloc[5:10, 2:4]
```

Sad man `[:,[` below here:

```
scores = data.loc[:,['score']]
print 'Mean score:', scores.mean()
```

No more sad man:

```
scores = data.loc[:, ['score']]
```
#### FutureWarning

Looks like you are using an outdated method that causes a FutureWarning

```
data.sort('chromSpan', ascending=False)
# should be:
data.sort_values(by='chromSpan', ascending=False)
```
#### Unexplained complicated feature:

```
chrM = data.loc[data['chrom'] == 'chrM']
chrM.plot(kind='bar', y='score',x='chromStart', xticks=[])
```

You might want to explain how the first line works. 
So far we have seen loc bracket notation with arrays of column names to pull.
Here the == operator doesn't work like a typical python list and they should probably be told that.
It's really convenient syntax but it's a pandas specific thing (returning an array of boolean that pandas knows about). You could also break this feature out into it's own example since we are introducing plotting in this example.
#### Missing some data files?

This code only finds one data file but it looks like it was written to process multiple.

```
import pandas
%matplotlib inline
filenames = glob.glob('data/*.bed') # Where is the data?
print filenames
filenames = filenames[0:3]
cols = ['chrom','chromStart','chromEnd','name','score','strand','level','signif','score2']

for f in filenames:
    print f
    data = pandas.read_table(f, header=None)
    data.columns = cols
    data.groupby('chrom').mean().plot(kind='bar',y='score', ylim=[0,250], title=f, figsize=(10,5))
```
#### First place mentioning whitespace

I expected to see mention of whitespace earlier in the presentation.  Possibly an example of mis-aligned code (IndentationError: unexpected indent) or something like that. Perhaps show that removing spaces changes how stuff works.
#### Cool but perhaps for an ipython notebook course.

If you are running out of time I would skip this one since you are going to show them how to do it from the command line next.

**Overall it looks good.**

**Comment by dleehr** [comment]
Thanks for the feedback

The inconsistent spacing and FutureWarning can be addressed, thanks!

> Unexplained complicated feature:
> You might want to explain how the first line works. 

Good point. This is covered during the workshop, and I take the participants through unpacking/decomposing it. but the concepts aren't written down. Unfortunately the square bracket syntax is a part of Pandas that's very alien to the python basics of function calls and simple list operations. I wonder if there's a simpler way to do `df.loc` without `[]`s

> 04 Missing data files

There are more files from bash lesson: https://github.com/Duke-GCB/GCB-Academy-2015-10-05/archive/materials-v0.1.zip I think we used those.

> 06 First place mentioning whitespace

This comes up in discussion earlier than part 6, but it's probably good to write it down where it first appears

> 07 Cool but perhaps for an ipython notebook course.

This is a (perhaps too) clever way to generate a few versions of files. It's not typical of how one would normally use a text editor but it's a little quicker to generate different versions and avoid switching between editor, viewer, and command-line.

In addition to writing hte script, it sets the stage for version control lesson the next day, leaving the participant with a bunch of iterations of the script.

**Comment by dleehr** [comment]
Thanks for the feedback. Formatting changes and comments have been added to master. We discussed in this week's meeting how to address the confusion/cleverness of 07.
